### ISSUE TITLE
Getting a git error

### ISSUE THREAD

**Issue by bnaman50** [oncletom/homebrew-brew#4]
Hey, 

Thanks for this great tool. I was trying to use it but it gave me an error as follows - 
`fatal: not a git repository (or any of the parent directories): .git`

Then I simply tried to run `cpdf -help` and it still gave me a similar error. 

I understand that this error implies that I am running some git command outside a git repository. But I was hoping that I could run this command in any directory. Could you please help me if I am missing something?

P.S. - I simply installed it using the following commands as per your suggestion in the readme file: 
```
brew tap oncletom/brew
brew install cpdf
``` 

Thanks, 
Naman

**Comment by thom4parisot** [comment]
Which version of homebrew do you have?

`brew tap oncletom/brew` will clone `https://github.com/oncletom/homebrew-brew`, and then cpdf is installed from `https://github.com/coherentgraphics/cpdf-binaries`.

Can you try again with `brew tap --debug --verbose oncletom/brew`?

**Comment by bnaman50** [comment]
Hey @oncletom , 

Thanks for your quick response. 

Homebrew version - 
```
$ brew --version
Homebrew 3.2.12
Homebrew/homebrew-core (git revision b2688cffc49; last commit 2021-09-17)
Homebrew/homebrew-cask (git revision 7764ed4222; last commit 2021-09-17)
```

I thought to install the `cpdf`, I just need to run `brew install cpdf`. I did not make use of any binaries. 


> Can you try again with brew tap --debug --verbose oncletom/brew?

Here are the results - 
```
$ brew tap --debug --verbose oncletom/brew
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
Updated 1 cask.
```

BTW, I think `cpdf` has been installed - 
```
$ which cpdf
/usr/local/bin/cpdf
```

**Comment by bnaman50** [comment]
Never mind, it actually worked this time. May be it was conflicting was the function that I had created - 
```
cpdf () {
	git stash -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile="$1" "${@:2}"
}
```

But now, it works. Thanks for your response. 

Naman

**Comment by thom4parisot** [comment]
Strange, but glad it works now 🙂
